### ISSUE TITLE
Pathy href - No Soft fails for "#" || ""

### ISSUE THREAD

**Issue by ejalfonzo** [Hedzer/Pathy#2]
href="#" || href=""

They both activate pathy:
- href="#" : throws error since app\routes\.html   :  **not found**
- href=""   : always takes you to index.html instead staying where it is

**Comment by ejalfonzo** [comment]
not having href="" fixes the problem

**Comment by Hedzer** [comment]
I've added some code so that Pathy doesn't attempt to navigate if there's no location hash or href.
